"""added coop to students

Revision ID: 00aeff3ba4ce
Revises: 8de77c3c9c35
Create Date: 2025-06-24 19:35:20.338370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00aeff3ba4ce'
down_revision = '8de77c3c9c35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ccop', sa.Boolean(), server_default=sa.text('True'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('ccop')

    # ### end Alembic commands ###
