"""undeleted sutff

Revision ID: 067207a0b37b
Revises: 3f18ad4979ac
Create Date: 2025-08-28 23:43:40.374997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '067207a0b37b'
down_revision = '3f18ad4979ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('offeredIn', sa.String(), nullable=False),
    sa.Column('subjectCode', sa.String(), nullable=False),
    sa.Column('catalogNumber', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('preReq', sa.String(), server_default='', nullable=False),
    sa.Column('coReq', sa.String(), server_default='', nullable=False),
    sa.Column('antiReq', sa.String(), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_name', sa.String(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('enrollment_capacity', sa.Integer(), nullable=False),
    sa.Column('enrollment_total', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sections')
    op.drop_table('courses')
    # ### end Alembic commands ###
