"""added first and last name to user schema

Revision ID: 147269e8e5f6
Revises: 2e08159f14c7
Create Date: 2025-06-29 01:13:12.246563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '147269e8e5f6'
down_revision = '2e08159f14c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=50), nullable=False, server_default='Default'))
        batch_op.add_column(sa.Column('last_name', sa.String(length=50), nullable=False, server_default='Default'))
        batch_op.drop_column('coop')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coop', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
