"""added ways to track courses

Revision ID: 16153bbbedf8
Revises: c86c38ad12e1
Create Date: 2025-08-29 00:39:29.374295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16153bbbedf8'
down_revision = 'c86c38ad12e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section_ids', sa.String(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('course_ids', sa.String(), nullable=False, server_default=''))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('course_ids')
        batch_op.drop_column('section_ids')

    # ### end Alembic commands ###
