"""updated courses

Revision ID: 1fe446a5b205
Revises: 6534b22b13dc
Create Date: 2025-08-28 23:14:05.463032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fe446a5b205'
down_revision = '6534b22b13dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('enrollConsentCode')
        batch_op.drop_column('gradingBasis')
        batch_op.drop_column('associatedAcademicGroupCode')
        batch_op.drop_column('courseComponentCode')
        batch_op.drop_column('descriptionAbbreviated')
        batch_op.drop_column('dropConsentCode')
        batch_op.drop_column('associatedAcademicOrgCode')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('associatedAcademicOrgCode', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('dropConsentCode', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('descriptionAbbreviated', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('courseComponentCode', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('associatedAcademicGroupCode', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('gradingBasis', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('enrollConsentCode', sa.VARCHAR(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
