"""added path

Revision ID: 250a549c3f24
Revises: c08b99d16fb0
Create Date: 2025-08-25 22:31:37.301946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '250a549c3f24'
down_revision = 'c08b99d16fb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.String(), server_default='', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('path')

    # ### end Alembic commands ###
