"""removed started year and semester to use started_term

Revision ID: 28ba6c2af670
Revises: d46852e9bdaf
Create Date: 2025-10-09 21:02:09.069806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28ba6c2af670'
down_revision = 'd46852e9bdaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('started_term', sa.Integer(), server_default=sa.text('1255'), nullable=False))
        batch_op.drop_column('started_month')
        batch_op.drop_column('started_year')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('started_year', sa.INTEGER(), server_default=sa.text('2024'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('started_month', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('started_term')

    # ### end Alembic commands ###
