"""added Sequence and Specialization

Revision ID: 2929dfde3c61
Revises: 7c72a76f094f
Create Date: 2025-06-07 12:23:25.334798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2929dfde3c61'
down_revision = '7c72a76f094f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sequences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specializations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('minors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialization_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sequence_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'sequences', ['sequence_id'], ['id'])
        batch_op.create_foreign_key(None, 'specializations', ['specialization_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('sequence_id')
        batch_op.drop_column('specialization_id')

    with op.batch_alter_table('minors', schema=None) as batch_op:
        batch_op.drop_column('name')

    op.drop_table('specializations')
    op.drop_table('sequences')
    # ### end Alembic commands ###
