"""updated majors

Revision ID: 2d4ff3cd403a
Revises: 8ec102ed1fb5
Create Date: 2025-06-15 11:15:59.352668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d4ff3cd403a'
down_revision = '8ec102ed1fb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('major', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coop', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False))
        batch_op.add_column(sa.Column('regular', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False))
        batch_op.drop_column('coop_offered')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('major', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coop_offered', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
        batch_op.drop_column('regular')
        batch_op.drop_column('coop')

    # ### end Alembic commands ###
