"""added specialization major

Revision ID: 36df2a31d258
Revises: 5ae984ea238d
Create Date: 2025-06-21 02:53:31.413463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36df2a31d258'
down_revision = '5ae984ea238d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specializations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('major_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'major', ['major_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specializations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('major_id')

    # ### end Alembic commands ###
