"""deleted stuff

Revision ID: 3f18ad4979ac
Revises: 1fe446a5b205
Create Date: 2025-08-28 23:40:52.198600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f18ad4979ac'
down_revision = '1fe446a5b205'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('courses')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('courseId', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('offeredIn', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('subjectCode', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('catalogNumber', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('preReq', sa.VARCHAR(), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('coReq', sa.VARCHAR(), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('antiReq', sa.VARCHAR(), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='courses_pkey')
    )
    # ### end Alembic commands ###
