"""updated course

Revision ID: 3f4132f65538
Revises: 067207a0b37b
Create Date: 2025-08-28 23:44:42.054806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f4132f65538'
down_revision = '067207a0b37b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(), nullable=False))
        batch_op.drop_column('catalogNumber')
        batch_op.drop_column('subjectCode')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subjectCode', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('catalogNumber', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('code')

    # ### end Alembic commands ###
