"""migrate commit

Revision ID: 49a05be7fb9f
Revises: d7af4cf63fae
Create Date: 2025-06-21 18:58:29.915971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49a05be7fb9f'
down_revision = 'd7af4cf63fae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('major_sequence',
    sa.Column('major_id', sa.Integer(), nullable=False),
    sa.Column('sequence_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['major_id'], ['major.id'], ),
    sa.ForeignKeyConstraint(['sequence_id'], ['sequences.id'], ),
    sa.PrimaryKeyConstraint('major_id', 'sequence_id')
    )
    with op.batch_alter_table('specializations', schema=None) as batch_op:
        batch_op.drop_column('is_option')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specializations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_option', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))

    op.drop_table('major_sequence')
    # ### end Alembic commands ###
