"""added is_option to specializations

Revision ID: 55e6d69852df
Revises: d7af4cf63fae
Create Date: 2025-06-21 13:02:20.962842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55e6d69852df'
down_revision = 'd7af4cf63fae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specializations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_option', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specializations', schema=None) as batch_op:
        batch_op.drop_column('is_option')

    # ### end Alembic commands ###
