"""updated course

Revision ID: 569f9059acfd
Revises: 3f4132f65538
Create Date: 2025-08-29 00:03:05.652501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '569f9059acfd'
down_revision = '3f4132f65538'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('prereqs', sa.String(), server_default='', nullable=False))
        batch_op.add_column(sa.Column('coreqs', sa.String(), server_default='', nullable=False))
        batch_op.add_column(sa.Column('antireqs', sa.String(), server_default='', nullable=False))
        batch_op.drop_column('preReq')
        batch_op.drop_column('antiReq')
        batch_op.drop_column('coReq')
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('coReq', sa.VARCHAR(), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('antiReq', sa.VARCHAR(), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('preReq', sa.VARCHAR(), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
        batch_op.drop_column('antireqs')
        batch_op.drop_column('coreqs')
        batch_op.drop_column('prereqs')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
