"""empty message

Revision ID: 5a1cd27a42b7
Revises: 61dd5c535a0a
Create Date: 2025-05-01 22:42:44.133968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a1cd27a42b7'
down_revision = '61dd5c535a0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jwt_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refresh_token_string', sa.String(), nullable=False))
        batch_op.drop_column('refresh_Token_string')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jwt_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refresh_Token_string', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('refresh_token_string')

    # ### end Alembic commands ###
