"""connected Programs and Sequences dbs

Revision ID: 5a94ae425ecd
Revises: a4408a22a523
Create Date: 2025-12-27 12:06:15.924481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a94ae425ecd'
down_revision = 'a4408a22a523'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('program_sequence',
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('sequence_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.ForeignKeyConstraint(['sequence_id'], ['sequences.id'], ),
    sa.PrimaryKeyConstraint('program_id', 'sequence_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('program_sequence')
    # ### end Alembic commands ###
