"""removed specialization major

Revision ID: 5ae984ea238d
Revises: a17b7174cb7c
Create Date: 2025-06-21 02:52:48.262186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ae984ea238d'
down_revision = 'a17b7174cb7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specializations', schema=None) as batch_op:
        batch_op.drop_constraint('specializations_major_id_fkey', type_='foreignkey')
        batch_op.drop_column('major_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specializations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('major_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('specializations_major_id_fkey', 'major', ['major_id'], ['id'])

    # ### end Alembic commands ###
