"""updated specialization

Revision ID: 5c88a603cb0b
Revises: bce3477385a9
Create Date: 2025-06-21 01:36:59.914829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c88a603cb0b'
down_revision = 'bce3477385a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specializations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specializations', schema=None) as batch_op:
        batch_op.drop_column('link')

    # ### end Alembic commands ###
