"""updating majors and students

Revision ID: 5e5a1cbb307d
Revises: 641072d282c5
Create Date: 2025-06-13 20:38:39.992084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e5a1cbb307d'
down_revision = '641072d282c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('major_student',
    sa.Column('students_id', sa.Integer(), nullable=False),
    sa.Column('major_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['major_id'], ['major.id'], ),
    sa.ForeignKeyConstraint(['students_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('students_id', 'major_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('major_student')
    # ### end Alembic commands ###
