"""empty message

Revision ID: 61dd5c535a0a
Revises: f3ecb342f06d
Create Date: 2025-05-01 22:38:52.703382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61dd5c535a0a'
down_revision = 'f3ecb342f06d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jwt_token',
    sa.Column('jwt_token_id', sa.Integer(), nullable=False),
    sa.Column('refresh_Token_string', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('jwt_token_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('academic_info_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('academic_info_id', sa.INTEGER(), autoincrement=False, nullable=True))

    op.drop_table('jwt_token')
    # ### end Alembic commands ###
