"""updating majors

Revision ID: 641072d282c5
Revises: eb4ea015f475
Create Date: 2025-06-13 20:30:33.611916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '641072d282c5'
down_revision = 'eb4ea015f475'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_second_major_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('users_major_id_fkey', type_='foreignkey')
        batch_op.drop_column('second_major_id')
        batch_op.drop_column('major_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('major_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('second_major_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('users_major_id_fkey', 'major', ['major_id'], ['id'])
        batch_op.create_foreign_key('users_second_major_id_fkey', 'major', ['second_major_id'], ['id'])

    # ### end Alembic commands ###
