"""Added reqs

Revision ID: 6534b22b13dc
Revises: a98f60cce8f0
Create Date: 2025-08-28 14:26:49.837190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6534b22b13dc'
down_revision = 'a98f60cce8f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preReq', sa.String(), server_default='', nullable=False))
        batch_op.add_column(sa.Column('coReq', sa.String(), server_default='', nullable=False))
        batch_op.add_column(sa.Column('antiReq', sa.String(), server_default='', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('antiReq')
        batch_op.drop_column('coReq')
        batch_op.drop_column('preReq')

    # ### end Alembic commands ###
