"""migrate commit

Revision ID: 69d18c4c274e
Revises: 5a1cd27a42b7
Create Date: 2025-05-27 22:26:40.192522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69d18c4c274e'
down_revision = '5a1cd27a42b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False))
        batch_op.add_column(sa.Column('verification_code', sa.Integer(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('verification_expiration', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('verification_expiration')
        batch_op.drop_column('verification_code')
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###
