"""removed expiration

Revision ID: 6b5362096617
Revises: 69d18c4c274e
Create Date: 2025-05-27 23:00:49.009326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b5362096617'
down_revision = '69d18c4c274e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('verification_expiration')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_expiration', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
