"""added minors

Revision ID: 7c72a76f094f
Revises: aad077da5a03
Create Date: 2025-06-06 21:17:59.203438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c72a76f094f'
down_revision = 'aad077da5a03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('minors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('minor_user',
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('minor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['minor_id'], ['minors.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('users_id', 'minor_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('minor_user')
    op.drop_table('minors')
    # ### end Alembic commands ###
