"""fixed student specialization relationship

Revision ID: 8ec102ed1fb5
Revises: d7f6662f939f
Create Date: 2025-06-14 14:23:55.319233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ec102ed1fb5'
down_revision = 'd7f6662f939f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specialization_student',
    sa.Column('spec_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['spec_id'], ['specializations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('spec_id', 'user_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_specialization_id_fkey', type_='foreignkey')
        batch_op.drop_column('specialization_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialization_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('users_specialization_id_fkey', 'specializations', ['specialization_id'], ['id'])

    op.drop_table('specialization_student')
    # ### end Alembic commands ###
