"""added student information

Revision ID: 995ec30ba721
Revises: 2929dfde3c61
Create Date: 2025-06-07 12:46:10.540869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '995ec30ba721'
down_revision = '2929dfde3c61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_term', sa.Integer(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('started_year', sa.Integer(), server_default=sa.text('2024'), nullable=False))
        batch_op.add_column(sa.Column('started_month', sa.Integer(), server_default=sa.text('9'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('started_month')
        batch_op.drop_column('started_year')
        batch_op.drop_column('current_term')

    # ### end Alembic commands ###
