"""used courseInfo instead of prereqs

Revision ID: 9c2976102e42
Revises: d8e55c449e49
Create Date: 2025-10-28 21:35:09.295201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c2976102e42'
down_revision = 'd8e55c449e49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('courseInfo', sa.String(), server_default='', nullable=False))
        batch_op.drop_column('coreqs')
        batch_op.drop_column('antireqs')
        batch_op.drop_column('prereqs')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prereqs', sa.VARCHAR(), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('antireqs', sa.VARCHAR(), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('coreqs', sa.VARCHAR(), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
        batch_op.drop_column('courseInfo')

    # ### end Alembic commands ###
