"""removed verification_expiration

Revision ID: 9d16fe3255b6
Revises: 54b84ec4521b
Create Date: 2025-05-27 23:05:45.564516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d16fe3255b6'
down_revision = '54b84ec4521b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('verification_expiration')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_expiration', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
