"""made the Programs database

Revision ID: a4408a22a523
Revises: e61465432748
Create Date: 2025-12-27 12:02:14.343512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4408a22a523'
down_revision = 'e61465432748'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('programType', sa.String(), nullable=False),
    sa.Column('groupName', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('degreeName', sa.String(), nullable=False),
    sa.Column('systemOfStudy', sa.String(), nullable=False),
    sa.Column('offeredByFaculties', sa.String(), nullable=False),
    sa.Column('availableTo', sa.String(), nullable=False),
    sa.Column('specializations', sa.String(), nullable=False),
    sa.Column('courseRequirements', sa.String(), nullable=False),
    sa.Column('courseLists', sa.String(), nullable=False),
    sa.Column('otherSections', sa.String(), nullable=False),
    sa.Column('relatedLinks', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('programs')
    # ### end Alembic commands ###
