"""Added groupName and groupCode

Revision ID: a6aa77ccf6b4
Revises: 9c2976102e42
Create Date: 2025-10-28 21:45:19.962131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6aa77ccf6b4'
down_revision = '9c2976102e42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('groupName', sa.String(), server_default='', nullable=False))
        batch_op.add_column(sa.Column('groupCode', sa.String(), server_default='', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('groupCode')
        batch_op.drop_column('groupName')

    # ### end Alembic commands ###
