"""added Course

Revision ID: a98f60cce8f0
Revises: 250a549c3f24
Create Date: 2025-08-27 11:16:57.211069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a98f60cce8f0'
down_revision = '250a549c3f24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('courseId', sa.String(), nullable=False),
    sa.Column('offeredIn', sa.String(), nullable=False),
    sa.Column('associatedAcademicGroupCode', sa.String(), nullable=False),
    sa.Column('associatedAcademicOrgCode', sa.String(), nullable=False),
    sa.Column('subjectCode', sa.String(), nullable=False),
    sa.Column('catalogNumber', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('descriptionAbbreviated', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('gradingBasis', sa.String(), nullable=False),
    sa.Column('courseComponentCode', sa.String(), nullable=False),
    sa.Column('enrollConsentCode', sa.String(), nullable=False),
    sa.Column('dropConsentCode', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('courses')
    # ### end Alembic commands ###
