"""Added majors

Revision ID: aad077da5a03
Revises: 
Create Date: 2025-06-06 20:32:44.527018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aad077da5a03'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('major',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('pass_hash', sa.String(), nullable=False),
    sa.Column('login_method', sa.Enum('email', 'google', 'apple', 'github', name='login_method'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('verification_code', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('verification_expiration', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('major_id', sa.Integer(), nullable=True),
    sa.Column('second_major_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['major_id'], ['major.id'], ),
    sa.ForeignKeyConstraint(['second_major_id'], ['major.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('jwt_token',
    sa.Column('jwt_token_id', sa.Integer(), nullable=False),
    sa.Column('refresh_token_string', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('jwt_token_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jwt_token')
    op.drop_table('users')
    op.drop_table('major')
    # ### end Alembic commands ###
