"""updated programs a little bit

Revision ID: b3295003c359
Revises: 8dd94013f6ed
Create Date: 2025-12-28 00:04:54.251565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3295003c359'
down_revision = '8dd94013f6ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('degreeId', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['url'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('degreeId')

    # ### end Alembic commands ###
