"""updated minors

Revision ID: bce3477385a9
Revises: 4541d3da7f44
Create Date: 2025-06-15 13:21:45.502759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bce3477385a9'
down_revision = '4541d3da7f44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('minors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('url', sa.String(), server_default='https://uwaterloo.ca/future-students/programs/minors', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('minors', schema=None) as batch_op:
        batch_op.drop_column('url')
        batch_op.drop_column('theme')

    # ### end Alembic commands ###
