"""deleted section for now

Revision ID: c86c38ad12e1
Revises: 569f9059acfd
Create Date: 2025-08-29 00:31:55.204555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c86c38ad12e1'
down_revision = '569f9059acfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sections')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sections',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('section_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('term_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('enrollment_capacity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('enrollment_total', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], name='sections_course_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='sections_pkey')
    )
    # ### end Alembic commands ###
