"""removed Major-Specialization connection

Revision ID: cdbbd473a504
Revises: 5c88a603cb0b
Create Date: 2025-06-21 02:24:16.038762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdbbd473a504'
down_revision = '5c88a603cb0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('major_specialization')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('major_specialization',
    sa.Column('major_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('specialization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['major_id'], ['major.id'], name='major_specialization_major_id_fkey'),
    sa.ForeignKeyConstraint(['specialization_id'], ['specializations.id'], name='major_specialization_specialization_id_fkey'),
    sa.PrimaryKeyConstraint('major_id', 'specialization_id', name='major_specialization_pkey')
    )
    # ### end Alembic commands ###
