"""added field to specs

Revision ID: d7af4cf63fae
Revises: 36df2a31d258
Create Date: 2025-06-21 03:15:52.323342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7af4cf63fae'
down_revision = '36df2a31d258'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specializations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('field', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specializations', schema=None) as batch_op:
        batch_op.drop_column('field')

    # ### end Alembic commands ###
