"""updatede majors

Revision ID: d7f6662f939f
Revises: 5e5a1cbb307d
Create Date: 2025-06-14 11:56:27.299561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7f6662f939f'
down_revision = '5e5a1cbb307d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('major', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(), server_default='https://uwaterloo.ca/future-students/programs/by-faculty', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('major', schema=None) as batch_op:
        batch_op.drop_column('url')

    # ### end Alembic commands ###
