"""updated sequence to have the new fields

Revision ID: e61465432748
Revises: a6aa77ccf6b4
Create Date: 2025-12-27 11:51:22.315420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e61465432748'
down_revision = 'a6aa77ccf6b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sequences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('legend', sa.String(), server_default=sa.text("'{}'"), nullable=False))
        batch_op.add_column(sa.Column('appliesTo', sa.String(), server_default='', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sequences', schema=None) as batch_op:
        batch_op.drop_column('appliesTo')
        batch_op.drop_column('legend')

    # ### end Alembic commands ###
