"""updated major spec relationship

Revision ID: e6c7abcbee4f
Revises: 6adf1dc2fcf3
Create Date: 2025-07-01 22:27:03.783436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6c7abcbee4f'
down_revision = '6adf1dc2fcf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('major_spec',
    sa.Column('spec_id', sa.Integer(), nullable=False),
    sa.Column('major_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['major_id'], ['major.id'], ),
    sa.ForeignKeyConstraint(['spec_id'], ['specializations.id'], ),
    sa.PrimaryKeyConstraint('spec_id', 'major_id')
    )
    with op.batch_alter_table('specializations', schema=None) as batch_op:
        batch_op.drop_constraint('specializations_major_id_fkey', type_='foreignkey')
        batch_op.drop_column('major_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specializations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('major_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('specializations_major_id_fkey', 'major', ['major_id'], ['id'])

    op.drop_table('major_spec')
    # ### end Alembic commands ###
