"""updated major

Revision ID: eb4ea015f475
Revises: f7ba21a80ffc
Create Date: 2025-06-07 13:20:12.407073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb4ea015f475'
down_revision = 'f7ba21a80ffc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('major_specialization',
    sa.Column('major_id', sa.Integer(), nullable=False),
    sa.Column('specialization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['major_id'], ['major.id'], ),
    sa.ForeignKeyConstraint(['specialization_id'], ['specializations.id'], ),
    sa.PrimaryKeyConstraint('major_id', 'specialization_id')
    )
    with op.batch_alter_table('major', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coop_offered', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('major', schema=None) as batch_op:
        batch_op.drop_column('coop_offered')

    op.drop_table('major_specialization')
    # ### end Alembic commands ###
