"""fixed typo

Revision ID: ef5ae93aa188
Revises: 00aeff3ba4ce
Create Date: 2025-06-24 19:36:15.039603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef5ae93aa188'
down_revision = '00aeff3ba4ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coop', sa.Boolean(), server_default=sa.text('True'), nullable=False))
        batch_op.drop_column('ccop')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ccop', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
        batch_op.drop_column('coop')

    # ### end Alembic commands ###
